version: "3"
services:
  backend:
    build:
      context: ./backend
    environment: 
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URL=mongodb://mongodb:27017/
    ports: 
      - "8080:8080"
    volumes:
      - ./backend:/app/
    depends_on:
      -  mongo  
    
  mongo:
    image: mongo
    container_name: mongodb
