version: "3"
services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ../nginx/conf.d:/etc/nginx/conf.d
  #     # - ./vanila-frontend:/usr/share/nginx/vanilla

  #   command: /bin/bash -c "nginx -g 'daemon off;'" 
  #   ports:
  #     - 80:80
  #   depends_on:
  #     # - frontend
  #     - backend
  
  # frontend:
  #   build: frontend
  #   command: >
  #     sh -c "yarn global add serve && serve -l 3000"
  #   stdin_open: true
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - backend

  backend:
    build:
      context: .
    environment: 
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URL=mongodb://mongodb:27017/
    volumes:
      - .:/server
    depends_on:
      -  mongo  
    ports: 
      - 8080:8080

  mongo:
    image: mongo
    container_name: mongodb
